### ISSUE TITLE
Error compiling version 9.13.0 with Visual Studio

### ISSUE THREAD

**Issue by RueFrank** [TheDIYGuy999/Rc_Engine_Sound_ESP32#89]
Hello,
I just can't seem to compile version 9.13.0. It worked perfectly with version 9.7.0. Can you help me? Here's the compiler output and two images.
Thanks

Compiling .pio\build\esp32dev\libb75\FastLED\platforms\esp\32\rmt_5\strip_rmt.cpp.o
Compiling .pio\build\esp32dev\libb75\FastLED\platforms\esp\32\spi_ws2812\strip_spi.cpp.o
In file included from .pio/libdeps/esp32dev/FastLED/src/platforms/esp/32/rmt_4/idf4_rmt_impl.h:15:0,
                 from .pio/libdeps/esp32dev/FastLED/src/platforms/esp/32/rmt_4/idf4_rmt.cpp:14:
.pio/libdeps/esp32dev/FastLED/src/platforms/esp/32/clock_cycles.h: In function 'uint32_t __cpu_hal_get_cycle_count()':
.pio/libdeps/esp32dev/FastLED/src/platforms/esp/32/clock_cycles.h:14:56: error: 'cpu_hal_get_cycle_count' was not declared in this scope
   return static_cast<uint32_t>(cpu_hal_get_cycle_count());
                                                        ^
*** [.pio\build\esp32dev\libb75\FastLED\platforms\esp\32\rmt_4\idf4_rmt.cpp.o] Error 1
In file included from .pio/libdeps/esp32dev/FastLED/src/platforms/esp/32/rmt_4/idf4_rmt_impl.h:15:0,
                 from .pio/libdeps/esp32dev/FastLED/src/platforms/esp/32/rmt_4/idf4_rmt_impl.cpp:17:
.pio/libdeps/esp32dev/FastLED/src/platforms/esp/32/clock_cycles.h: In function 'uint32_t __cpu_hal_get_cycle_count()':
.pio/libdeps/esp32dev/FastLED/src/platforms/esp/32/clock_cycles.h:14:56: error: 'cpu_hal_get_cycle_count' was not declared in this scope
   return static_cast<uint32_t>(cpu_hal_get_cycle_count());
                                                        ^
*** [.pio\build\esp32dev\libb75\FastLED\platforms\esp\32\rmt_4\idf4_rmt_impl.cpp.o] Error 1

Pic1
![Image](https://github.com/user-attachments/assets/59cfd0fd-bce3-4c38-b28b-4dfaa636d4c7)

Pic2

![Image](https://github.com/user-attachments/assets/650054b1-6414-4a0e-9756-57963622ad6b)

**Comment by TheDIYGuy999** [comment]
Hi, use the other FastLED library: 

![Image](https://github.com/user-attachments/assets/7a3092f2-2f5d-4ca8-846f-3f48c2e5741c)
